routes:
  /rss/:
    template: rss
    content_type: text/xml
  /categories/:
    template: page-categories
  /secondary-tags/:
    template: page-secondary-tags
  /series/:
    template: page-series
  /search/:
    template: page-search

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-blog
  /blog/:
    permalink: /blog/{slug}/
    template: blog
    filter: tag:blog
    data: tag.blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
