routes:
  /rss/:
    template: rss
    content_type: text/xml
  /categories/:
    template: page-categories
  /secondary-tags/:
    template: page-secondary-tags
  /series/:
    template: page-series
  /search/:
    template: page-search

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
